// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKTFtDBy0Ky5roYvnvuFhTp-0yagFz87E',
    appId: '1:292237971535:web:281786cdf66109bba91a3a',
    messagingSenderId: '292237971535',
    projectId: 'hadithi-ai',
    authDomain: 'hadithi-ai.firebaseapp.com',
    storageBucket: 'hadithi-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNhC82T7fa30ro-WbCI56FRs0u7Se3MhE',
    appId: '1:292237971535:android:ff43ee52b7495633a91a3a',
    messagingSenderId: '292237971535',
    projectId: 'hadithi-ai',
    storageBucket: 'hadithi-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSqNu3Ra1E39Dalpa2U72S0dFckKQhG5s',
    appId: '1:292237971535:ios:5d13dcfafa8d9b5ea91a3a',
    messagingSenderId: '292237971535',
    projectId: 'hadithi-ai',
    storageBucket: 'hadithi-ai.firebasestorage.app',
    iosBundleId: 'com.losingtech.hadithiai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSqNu3Ra1E39Dalpa2U72S0dFckKQhG5s',
    appId: '1:292237971535:ios:a161e79e72a9f945a91a3a',
    messagingSenderId: '292237971535',
    projectId: 'hadithi-ai',
    storageBucket: 'hadithi-ai.firebasestorage.app',
    iosBundleId: 'com.example.hadithiAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKTFtDBy0Ky5roYvnvuFhTp-0yagFz87E',
    appId: '1:292237971535:web:242ac87553ee11d1a91a3a',
    messagingSenderId: '292237971535',
    projectId: 'hadithi-ai',
    authDomain: 'hadithi-ai.firebaseapp.com',
    storageBucket: 'hadithi-ai.firebasestorage.app',
  );
}
